"use client";

import { useEffect, useRef, useState, useMemo, type FormEvent, type ReactNode } from 'react';
import { STATUSES, METRICS, blankAsset, cairoToday, monday, addDays, publishedInWeek, withoutMeta, type Asset, type Identity, type Settings, type Publication, type MetricKey } from './content/types';

const labels = { enzo: 'Enzo', hustliq: 'HustlIQ' };
const tabs = ['Overview', 'Ideas', 'Pipeline', 'Calendar', 'Editor', 'Results', 'Strategy'] as const;
const cadence: Identity[][] = [['enzo'], ['hustliq'], ['enzo', 'hustliq'], ['enzo'], ['hustliq'], ['enzo'], ['enzo', 'hustliq']];
const ready = ['READY', 'SCHEDULED'];
function download(name: string, text: string, type = 'text/plain') { const url = URL.createObjectURL(new Blob([text], { type })); const link = document.createElement('a'); link.href = url; link.download = name; link.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); }
function Field({ label, children }: { label: string; children: ReactNode }) { return <label className="cs-field"><span>{label}</span>{children}</label>; }
function Pill({ children }: { children: ReactNode }) { return <span className="cs-pill">{children}</span>; }
function display(value: number | null) { return value === null ? '—' : value.toLocaleString(); }

export default function ContentWorkspace({ apiBase }: { apiBase: string }) {
  const [assets, setAssets] = useState<Asset[]>([]);
  const [settings, setSettings] = useState<Settings | null>(null);
  const [loaded, setLoaded] = useState(false);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState('');
  const [notice, setNotice] = useState('');
  const [identity, setIdentity] = useState<'all' | Identity>('all');
  const [tab, setTab] = useState<typeof tabs[number]>('Overview');
  const [search, setSearch] = useState('');
  const [status, setStatus] = useState('all');
  const [week, setWeek] = useState(() => monday(cairoToday()));
  const [editing, setEditing] = useState<Asset | null>(null);
  const [editSettings, setEditSettings] = useState<Settings | null>(null);
  const [saveError, setSaveError] = useState('');
  const dialog = useRef<HTMLDialogElement>(null);
  const settingsDialog = useRef<HTMLDialogElement>(null);

  async function api(path: string, method = 'GET', body?: unknown) {
    const response = await fetch(`${apiBase}/api/content${path}`, { method, headers: { 'Content-Type': 'application/json' }, ...(body !== undefined ? { body: JSON.stringify(body) } : {}) });
    const data = await response.json().catch(() => ({}));
    if (!response.ok) throw new Error(data.error || 'Content could not be saved or loaded. Please try again.');
    return data;
  }
  async function load() {
    setBusy(true); setError('');
    try {
      let data = await api('');
      if (!data.initialized) { await api('/initialize', 'POST', {}); data = await api(''); }
      setAssets(data.assets); setSettings(data.settings); setLoaded(true);
    } catch (e) { setError(e instanceof Error ? e.message : 'Cannot reach content storage. Your existing records have not been replaced.'); }
    finally { setBusy(false); }
  }
  useEffect(() => { void load(); }, [apiBase]); // independent from Today data and its refresh cycle
  useEffect(() => { if (editing) dialog.current?.showModal(); else dialog.current?.close(); }, [!!editing]);
  useEffect(() => { if (editSettings) settingsDialog.current?.showModal(); else settingsDialog.current?.close(); }, [!!editSettings]);
  function open(asset: Asset) { setSaveError(''); setEditing(structuredClone(asset)); }
  function update<K extends keyof Asset>(key: K, value: Asset[K]) { setEditing(current => current ? { ...current, [key]: value } : current); }
  function updatePub(index: number, value: Partial<Publication>) { setEditing(current => current ? { ...current, publications: current.publications.map((p, i) => i === index ? { ...p, ...value } : p) } : current); }
  async function save(event: FormEvent) {
    event.preventDefault(); if (!editing || busy) return;
    setBusy(true); setSaveError('');
    try {
      const result: Asset = editing._id ? await api(`/assets/${editing._id}`, 'PUT', { revision: editing.revision, data: withoutMeta(editing) }) : await api('/assets', 'POST', withoutMeta(editing));
      setAssets(current => editing._id ? current.map(a => a._id === result._id ? result : a) : [...current, result]);
      setEditing(null); setNotice('Content record saved.');
    } catch (e) { setSaveError(e instanceof Error ? e.message : 'Save failed. Your changes are still here.'); }
    finally { setBusy(false); }
  }
  async function saveSettings(event: FormEvent) {
    event.preventDefault(); if (!editSettings || busy) return; setBusy(true); setSaveError('');
    try { const result = await api('/settings', 'PUT', { revision: editSettings.revision, data: withoutMeta(editSettings) }); setSettings(result); setEditSettings(null); setNotice('Experiment settings saved.'); }
    catch (e) { setSaveError(e instanceof Error ? e.message : 'Settings could not be saved.'); }
    finally { setBusy(false); }
  }
  const filtered = useMemo(() => assets.filter(a => identity === 'all' || a.identity === identity), [assets, identity]);
  const ideas = filtered.filter(a => (status === 'all' || a.status === status) && `${a.title} ${a.format} ${a.series} ${a.source}`.toLowerCase().includes(search.toLowerCase()));
  const finished = filtered.filter(a => ready.includes(a.status));
  const reserves = finished.filter(a => a.timing === 'Evergreen' && !a.scheduledDate);
  const published = filtered.filter(a => publishedInWeek(a, week));
  const filming = filtered.filter(a => a.status === 'READY TO FILM');
  const editor = filtered.filter(a => a.status !== 'ARCHIVED' && (['FILMED', 'EDITING'].includes(a.status) || a.editorStatus !== 'Not assigned'));
  const followups = filtered.filter(a => a.followUp && a.status !== 'ARCHIVED');
  const next = filtered.filter(a => a.scheduledDate && a.status !== 'ARCHIVED' && !['PUBLISHED', 'REVIEWED'].includes(a.status)).sort((a,b) => a.scheduledDate!.localeCompare(b.scheduledDate!));
  const metricRecords = filtered.flatMap(a => a.publications.filter(p => p.status === 'PUBLISHED').map(p => ({ a, p })));
  const budgetUsed = filtered.reduce((n, a) => n + (a.filmingDate && a.filmingDate >= week && a.filmingDate < addDays(week, 7) ? a.productionMinutes ?? 0 : 0), 0);
  const dayLabel = (date: string) => new Date(date + 'T12:00:00Z').toLocaleDateString('en', { weekday: 'short', month: 'short', day: 'numeric', timeZone: 'UTC' });
  const hasScript = (a: Asset) => a.script.trim().length > 0;
  const card = (a: Asset) => <button className={`cs-asset${tab === 'Calendar' && !hasScript(a) ? ' cs-asset-warning' : ''}`} key={a._id} onClick={() => open(a)}><span className={`cs-account ${a.identity}`}>{labels[a.identity]} · {a._id.slice(0, 12)}</span><strong>{a.title}</strong><span>{a.format || 'Format unassigned'}</span><div><Pill>{a.status}</Pill>{a.timing !== 'Unclassified' && <Pill>{a.timing}</Pill>}{tab === 'Calendar' && !hasScript(a) && <span className="cs-script-warning">Missing script</span>}</div></button>;
  const empty = (text: string) => <p className="cs-empty">{text}</p>;
  const brief = (a: Asset) => `${labels[a.identity]} — ${a.title}\n\nFormat: ${a.format}\nScript / talking points:\n${a.script || 'Not written'}\n\nFootage / assets:\n${a.assets || 'Not added'}\n\nEditor notes:\n${a.editorBrief || 'Not added'}\n\nEvidence:\n${a.evidence || 'Needs review'}\nPrivacy: ${a.privacy}\nPlanned publication: ${a.scheduledDate || 'Unassigned'}\n`;

  return <section className="content-workspace">
    <div className="cs-heading"><div><p className="eyebrow">Enzo × HustlIQ</p><h1>Content studio</h1><p>Capture the work. Make the video. Learn what connects.</p></div><div className="cs-actions"><button disabled={!loaded || busy} onClick={() => { setSaveError(''); setEditSettings(settings ? { ...settings } : null); }}>Experiment settings</button><button className="cs-primary" disabled={!loaded || busy} onClick={() => open(blankAsset(identity === 'all' ? 'enzo' : identity))}>+ Capture idea</button></div></div>
    {error && <div className="cs-error" role="alert">{error} <button disabled={busy} onClick={() => void load()}>Retry loading</button></div>}
    {notice && <div className="cs-notice" role="status">{notice}<button aria-label="Dismiss notification" onClick={() => setNotice('')}>×</button></div>}
    <div className="cs-identities" role="group" aria-label="Content identity">
      {(['all', 'enzo', 'hustliq'] as const).map(id => <button key={id} aria-pressed={identity === id} className={identity === id ? 'active' : ''} onClick={() => setIdentity(id)}><strong>{id === 'all' ? 'All accounts' : labels[id]}</strong><span>{id === 'all' ? 'One asset · three platforms' : id === 'enzo' ? 'Personal · Founder, stories & experiments' : 'Company · Distribution & first users'}</span></button>)}
    </div>
    <div className="cs-tabs" role="group" aria-label="Content views">{tabs.map(name => <button aria-pressed={tab === name} className={tab === name ? 'active' : ''} key={name} onClick={() => setTab(name)}>{name}{name === 'Ideas' && loaded ? ` · ${filtered.length}` : ''}</button>)}</div>
    {!loaded ? <div className="cs-empty" role="status">{busy ? 'Loading your content workspace…' : 'Content storage is unavailable. Use Retry loading above.'}</div> : <>
    {tab === 'Overview' && <>
      <div className="cs-stats"><div><span>Published this week</span><strong>{published.length}<small> / {identity === 'enzo' ? settings!.enzoWeekly : identity === 'hustliq' ? settings!.hustliqWeekly : settings!.enzoWeekly + settings!.hustliqWeekly}</small></strong><p>{dayLabel(week)} — {dayLabel(addDays(week, 6))}</p></div><div><span>Ready to film</span><strong>{filming.length}</strong><p>Talking points and assets prepared</p></div><div><span>Finished reserves</span><strong>{reserves.length}<small> / {settings!.backlogTarget}</small></strong><p>Evergreen, edited, not yet assigned a date</p></div><div><span>Five-week experiment</span><strong className="cs-text-stat">{settings!.startDate ? 'Start date set' : 'Not started'}</strong><p>{settings!.startDate ? `${settings!.startDate} → ${addDays(settings!.startDate, 34)}` : 'Set the publishing start when you are ready'}</p></div></div>
      <div className="cs-grid"><section className="cs-panel"><div className="cs-panel-heading"><h2>Next recording batch</h2><button onClick={() => setTab('Pipeline')}>View pipeline →</button></div>{filming.length ? filming.slice(0, 6).map(card) : empty('No videos are ready to film yet. Open an idea, prepare its talking points and assets, then set Ready to film.')}</section><section className="cs-panel"><div className="cs-panel-heading"><h2>Publishing next</h2><button onClick={() => setTab('Calendar')}>View calendar →</button></div>{next.length ? next.slice(0, 4).map(a => <div key={a._id}><small>{a.scheduledDate}</small>{card(a)}</div>) : empty('Your calendar has room for 5 Enzo and 4 HustlIQ videos. No titles or publication dates have been committed.')}</section><section className="cs-panel"><div className="cs-panel-heading"><h2>With the editor</h2><button onClick={() => setTab('Editor')}>Open queue →</button></div>{editor.length ? editor.slice(0, 4).map(card) : empty('Nothing handed off yet. Recorded footage and editor briefs will appear here.')}<p className="cs-muted">Friend helping for approximately one month. Expected turnaround: under three days; confirm individual deadlines.</p></section><section className="cs-panel"><h2>Follow-up opportunities</h2>{followups.length ? followups.slice(0, 4).map(a => <button className="cs-asset" key={a._id} onClick={() => open(a)}><strong>{a.title}</strong><span>{a.followUp}</span></button>) : empty('Record the next question, sequel, or experiment when you review a video.')}<p className="cs-muted">Logged production this week: {budgetUsed} minutes. Missing time entries are not estimates.</p></section></div>
    </>}
    {tab === 'Ideas' && <><div className="cs-toolbar"><Field label="Search ideas"><input placeholder="Title, format, series, or source" value={search} onChange={e => setSearch(e.target.value)} /></Field><Field label="Production status"><select value={status} onChange={e => setStatus(e.target.value)}><option value="all">All statuses</option>{STATUSES.map(s => <option key={s}>{s}</option>)}</select></Field><button onClick={() => download('mizan-content-records.json', JSON.stringify({ assets: filtered, settings }, null, 2), 'application/json')}>Export records</button></div><p className="cs-muted">Supplied ideas are candidates. Confirm experiences, opinions, evidence, and permissions before scripting. Hooks stay separate.</p><div className="cs-table-wrap"><table><thead><tr><th>Identity / ID</th><th>Working concept</th><th>Format</th><th>Status</th><th>Priority</th><th>Timing</th></tr></thead><tbody>{ideas.map(a => <tr key={a._id}><td><span className={`cs-account ${a.identity}`}>{labels[a.identity]}</span><small>{a._id.slice(0, 12)}</small></td><td><button className="cs-title-button" onClick={() => open(a)}>{a.title}</button></td><td>{a.format || '—'}</td><td><Pill>{a.status}</Pill></td><td>{a.priority}</td><td>{a.timing}</td></tr>)}</tbody></table>{!ideas.length && empty('No matching ideas. Try another search or capture a new one.')}</div></>}
    {tab === 'Pipeline' && <><p className="cs-muted">Open a card to update its status, footage, script, or handoff. No work is marked complete automatically.</p><div className="cs-board">{STATUSES.map(s => <section className="cs-lane" key={s}><h2>{s}<span>{filtered.filter(a => a.status === s).length}</span></h2>{filtered.filter(a => a.status === s).map(card)}{!filtered.some(a => a.status === s) && <p className="cs-muted">No assets</p>}</section>)}</div></>}
    {tab === 'Calendar' && <><div className="cs-toolbar"><button aria-label="Previous week" onClick={() => setWeek(addDays(week, -7))}>← Previous</button><Field label="Week containing"><input type="date" value={week} onChange={e => e.target.value && setWeek(monday(e.target.value))} /></Field><button aria-label="Next week" onClick={() => setWeek(addDays(week, 7))}>Next →</button></div><p className="cs-muted">Baseline: 5 Enzo + 4 HustlIQ. Aim for 6 planned and 3 timely assets. Ideas without scripts are flagged before filming or publishing. Dates use Cairo.</p><div className="cs-calendar">{cadence.map((ids, day) => { const date = addDays(week, day); const assigned = filtered.filter(a => a.status !== 'ARCHIVED' && (a.scheduledDate === date || a.publications.some(p => p.status !== 'DRAFT' && p.date === date))); return <section key={day} className="cs-day"><h2>{dayLabel(date)}</h2>{assigned.map(card)}{ids.filter(id => identity === 'all' || identity === id).map(id => <div className="cs-slot" key={id}><span className={`cs-account ${id}`}>{labels[id]} baseline slot</span><select aria-label={`Assign ${labels[id]} idea to ${date}`} value="" onChange={e => { const a = assets.find(a => a._id === e.target.value); if (a) open({ ...a, scheduledDate: date }); }}><option value="">Choose an idea…</option>{assets.filter(a => a.identity === id && !['PUBLISHED', 'REVIEWED', 'ARCHIVED'].includes(a.status)).map(a => <option key={a._id} value={a._id}>{hasScript(a) ? a.title : `⚠ Missing script — ${a.title}`}</option>)}</select></div>)}</section>; })}</div></>}
    {tab === 'Editor' && <><div className="cs-panel-heading"><div><h2>Editor handoff</h2><p className="cs-muted">Footage, talking points, evidence, and edit notes travel with each asset.</p></div><Pill>Target turnaround: under {settings!.editorTurnaroundDays} days</Pill></div>{editor.length ? <div className="cs-grid">{editor.map(a => <section className="cs-panel" key={a._id}>{card(a)}<p><strong>{a.editorStatus}</strong> · Filming: {a.filmingDate || 'Unassigned'} · Publish: {a.scheduledDate || 'Unassigned'}</p><p className="cs-prewrap">{a.editorBrief || 'Editor brief not written yet.'}</p><button onClick={() => download(`${a._id}-editor-brief.txt`, brief(a))}>Download editor brief</button></section>)}</div> : empty('No footage is in the editor queue. Set a recorded asset to Filmed, or assign its editor status.')}<section className="cs-panel cs-spaced"><h2>Finished evergreen backlog · {reserves.length}</h2>{reserves.length ? <div className="cs-grid">{reserves.map(card)}</div> : empty('Finished evergreen videos without publication dates will appear here. Time-sensitive videos do not count toward this reserve.')}</section></>}
    {tab === 'Results' && <><h2>Performance & learning</h2><p className="cs-muted">Record each platform separately. Blank means unknown. Compare similar publication ages; views alone do not decide the winner.</p>{metricRecords.length ? <div className="cs-table-wrap"><table><thead><tr><th>Video</th><th>Platform / dates</th><th>Views</th><th>Follows</th><th>Shares / saves</th><th>Qualified leads</th><th>Customers</th></tr></thead><tbody>{metricRecords.map(({a,p}) => <tr key={`${a._id}-${p.platform}`}><td><button className="cs-title-button" onClick={() => open(a)}>{a.title}</button><small>{labels[a.identity]} · {a.format}</small></td><td>{p.platform}<small>Published {p.date || '—'}<br/>Measured {p.measuredAt || '—'}</small>{p.url && <a href={p.url} target="_blank" rel="noreferrer">Open post ↗</a>}</td><td>{display(p.metrics.views)}</td><td>{display(p.metrics.followersGained)}</td><td>{display(p.metrics.shares)} / {display(p.metrics.saves)}</td><td>{display(p.metrics.leads)}</td><td>{display(p.metrics.customers)}</td></tr>)}</tbody></table></div> : empty('No published results yet. Open an asset and record its platform upload and metrics after publication.')}<div className="cs-grid cs-spaced"><section className="cs-panel"><h2>Enzo: investment in the founder</h2><p>Retention, follows, returning viewers, thoughtful comments, and requests for the next update.</p></section><section className="cs-panel"><h2>HustlIQ: the right founders</h2><p>Relevant conversations, qualified leads, service requests, customers, and revenue when attribution exists.</p></section></div><section className="cs-panel cs-spaced"><h2>Five-week review</h2><p>Find 2–3 repeatable formats per identity. Review audience quality, follow or business conversion, production time, and whether the format remains sustainable without the editor. Record a decision and follow-up on each reviewed asset.</p><p>{settings!.startDate ? `Review due ${addDays(settings!.startDate, 35)}.` : 'Review date will be set when the experiment starts.'}</p></section></>}
    {tab === 'Strategy' && <Strategy settings={settings!} onEdit={() => { setSaveError(''); setEditSettings({ ...settings! }); }} />}
    </>}

    <dialog className="cs-dialog" ref={dialog} aria-labelledby="cs-record-title" onCancel={e => { if (busy) e.preventDefault(); else setEditing(null); }}>
      {editing && <form onSubmit={save}><header className="cs-dialog-header"><div><p className="eyebrow">{editing._id || 'New idea'} · {labels[editing.identity]}</p><h2 id="cs-record-title">Content record</h2></div><button type="button" disabled={busy} onClick={() => setEditing(null)} aria-label="Close content record">×</button></header><div className="cs-dialog-body" inert={busy}>
        {saveError && <p className="cs-error" role="alert">{saveError}</p>}
        <Field label="Working concept / title"><input required maxLength={300} value={editing.title} onChange={e => update('title', e.target.value)} /></Field>
        <div className="cs-fields"><Field label="Identity"><select value={editing.identity} onChange={e => update('identity', e.target.value as Identity)}><option value="enzo">Enzo · Personal</option><option value="hustliq">HustlIQ · Company</option></select></Field><Field label="Status"><select value={editing.status} onChange={e => update('status', e.target.value as Asset['status'])}>{STATUSES.map(s => <option key={s}>{s}</option>)}</select></Field><Field label="Priority"><select value={editing.priority} onChange={e => update('priority', e.target.value as Asset['priority'])}>{['Normal', 'High', 'Low'].map(s => <option key={s}>{s}</option>)}</select></Field><Field label="Timing"><select value={editing.timing} onChange={e => update('timing', e.target.value as Asset['timing'])}>{['Unclassified', 'Evergreen', 'Timely'].map(s => <option key={s}>{s}</option>)}</select></Field></div>
        <div className="cs-fields">{(['territory', 'format', 'series'] as const).map(key => <Field key={key} label={key === 'territory' ? 'Content territory' : key === 'format' ? 'Format' : 'Recurring series'}><input value={editing[key]} onChange={e => update(key, e.target.value)} /></Field>)}</div>
        <details open><summary>Source, research & evidence</summary>{([['source', 'What actually happened / source'], ['experiment', 'Related startup experiment'], ['research', 'Research still needed'], ['evidence', 'Confirmed facts and sources'], ['assets', 'Footage, screenshots & asset links']] as const).map(([key,label]) => <Field key={key} label={label}><textarea rows={3} value={editing[key]} onChange={e => update(key, e.target.value)} /></Field>)}<Field label="Privacy / permission"><select value={editing.privacy} onChange={e => update('privacy', e.target.value)}>{['Needs review', 'Public material', 'Anonymized', 'Permission confirmed', 'Private — do not publish'].map(s => <option key={s}>{s}</option>)}</select></Field></details>
        <details><summary>Hooks, talking points & editor brief</summary>{([['hooks', 'Hooks — optional, separate creative stage'], ['script', 'Script / talking points'], ['editorBrief', 'Editor brief: structure, pacing, key moments, what not to cut, length, CTA']] as const).map(([key,label]) => <Field key={key} label={label}><textarea rows={6} value={editing[key]} onChange={e => update(key, e.target.value)} /></Field>)}</details>
        <details open><summary>Production & scheduling</summary><div className="cs-fields"><Field label="Filming session date"><input type="date" value={editing.filmingDate || ''} onChange={e => update('filmingDate', e.target.value || null)} /></Field><Field label="Planned publication date"><input type="date" value={editing.scheduledDate || ''} onChange={e => update('scheduledDate', e.target.value || null)} /></Field><Field label="Editor status"><select value={editing.editorStatus} onChange={e => update('editorStatus', e.target.value)}>{['Not assigned', 'Queued', 'Editing', 'Needs revision', 'Delivered'].map(s => <option key={s}>{s}</option>)}</select></Field><Field label="Your production time (minutes)"><input type="number" min="0" value={editing.productionMinutes ?? ''} onChange={e => update('productionMinutes', e.target.value === '' ? null : Number(e.target.value))} /></Field></div></details>
        <details><summary>Platform uploads & performance</summary><p className="cs-muted">One video stays one asset. Enter actual platform results; leave unavailable numbers blank. Add currency and attribution basis in the platform notes for revenue.</p>{editing.publications.map((p,index) => <section className="cs-publication" key={p.platform}><h3>{p.platform}</h3><div className="cs-fields"><Field label="Upload status"><select value={p.status} onChange={e => updatePub(index, { status: e.target.value as Publication['status'] })}>{['DRAFT', 'SCHEDULED', 'PUBLISHED'].map(s => <option key={s}>{s}</option>)}</select></Field><Field label="Upload date"><input type="date" value={p.date || ''} onChange={e => updatePub(index, { date: e.target.value || null })} /></Field><Field label="Metrics measured on"><input type="date" value={p.measuredAt || ''} onChange={e => updatePub(index, { measuredAt: e.target.value || null })} /></Field></div><Field label="Post URL"><input type="url" placeholder="https://…" value={p.url} onChange={e => updatePub(index, { url: e.target.value })} /></Field><div className="cs-fields">{Object.entries(METRICS).map(([key,label]) => <Field key={key} label={label}><input type="number" step="any" min="0" value={p.metrics[key as MetricKey] ?? ''} onChange={e => updatePub(index, { metrics: { ...p.metrics, [key]: e.target.value === '' ? null : Number(e.target.value) } })} /></Field>)}</div><Field label="Audience quality, comments, attribution & context"><textarea rows={3} value={p.notes} onChange={e => updatePub(index, { notes: e.target.value })} /></Field></section>)}</details>
        <details><summary>Review & follow-up</summary><Field label="What worked, what did not, and your next decision"><textarea rows={4} value={editing.notes} onChange={e => update('notes', e.target.value)} /></Field><Field label="Follow-up idea / sequel"><textarea rows={3} value={editing.followUp} onChange={e => update('followUp', e.target.value)} /></Field><Field label="Related asset IDs (comma-separated)"><input value={editing.relatedIds.join(', ')} onChange={e => update('relatedIds', e.target.value.split(',').map(s => s.trim()).filter(Boolean))} /></Field></details>
        </div><footer className="cs-dialog-footer"><button type="button" disabled={busy} onClick={() => setEditing(null)}>Cancel</button><button type="button" onClick={() => download(`${editing._id || 'idea'}-editor-brief.txt`, brief(editing))}>Download brief</button><button className="cs-primary" disabled={busy} type="submit">{busy ? 'Saving…' : 'Save changes'}</button></footer></form>}
    </dialog>
    <dialog className="cs-dialog cs-settings" ref={settingsDialog} aria-labelledby="cs-settings-title" onCancel={e => { if (busy) e.preventDefault(); else setEditSettings(null); }}>
      {editSettings && <form onSubmit={saveSettings}><header className="cs-dialog-header"><h2 id="cs-settings-title">Experiment settings</h2><button type="button" disabled={busy} onClick={() => setEditSettings(null)} aria-label="Close experiment settings">×</button></header><div className="cs-dialog-body" inert={busy}>{saveError && <p className="cs-error" role="alert">{saveError}</p>}<p>Publishing starts only when you set a start date. Changing a target does not move existing calendar entries.</p><div className="cs-fields">{([['startDate', 'Five-week publishing start'], ['firstRecordingDate', 'First recording session'], ['editorAvailableUntil', 'Editor available until']] as const).map(([key,label]) => <Field key={key} label={label}><input type="date" value={editSettings[key] || ''} onChange={e => setEditSettings({ ...editSettings, [key]: e.target.value || null })} /></Field>)}{([['enzoWeekly','Enzo videos / week',30], ['hustliqWeekly','HustlIQ videos / week',30], ['dailyMinutes','Normal daily time budget (minutes)',1440], ['firstRecordingMinutes','First session budget (minutes)',1440], ['editorTurnaroundDays','Editor turnaround ceiling (days)',30], ['backlogTarget','Finished reserve target',100]] as const).map(([key,label,max]) => <Field key={key} label={label}><input required type="number" min="0" max={max} value={editSettings[key]} onChange={e => setEditSettings({ ...editSettings, [key]: Number(e.target.value) })} /></Field>)}</div><Field label="Capacity notes and reasons for changing the baseline"><textarea rows={4} value={editSettings.notes} onChange={e => setEditSettings({ ...editSettings, notes: e.target.value })} /></Field></div><footer className="cs-dialog-footer"><button type="button" disabled={busy} onClick={() => setEditSettings(null)}>Cancel</button><button type="submit" className="cs-primary" disabled={busy}>{busy ? 'Saving…' : 'Save settings'}</button></footer></form>}
    </dialog>
  </section>;
}

function Strategy({ settings, onEdit }: { settings: Settings; onEdit: () => void }) {
  return <><div className="cs-grid"><section className="cs-panel"><span className="cs-account enzo">Enzo · Personal accounts</span><h2>Follow the founder</h2><p>A funny, curious founder building and trying things. Stories, experiments, opinions, failures, AI builds, and occasional life moments.</p><ul><li>English TikTok: new creator account.</li><li>Instagram: transition the existing personal account.</li><li>YouTube Shorts: English short-form.</li><li>Minimal traditional teaching in the first five weeks.</li><li>Humor through personality and situations; no forced persona.</li><li>Primary action: follow Enzo and return for the journey.</li></ul><p>Enzo should remain interesting beyond HustlIQ. No automatic sales CTA.</p></section><section className="cs-panel"><span className="cs-account hustliq">HustlIQ · Company accounts</span><h2>Understand the distribution problem</h2><p>The ugly reality of getting people to notice, try, and buy a startup. Dedicated TikTok, Instagram Reels, and YouTube Shorts accounts.</p><ul><li>Technical founders with a real or near-launch product and no repeatable acquisition channel.</li><li>Current wedge: distribution execution and first users.</li><li>Find → Reach → Learn → Refine.</li><li>HustlIQ researches and helps design tests; founders perform customer interactions.</li><li>Human review, source evidence, founder approval, no blind auto-posting.</li><li>Primary action: relevant founders investigate the current offer.</li></ul></section></div>
  <section className="cs-panel cs-spaced"><h2>Current reality</h2><p>No content recorded or published at setup. Research has started for three different business models. Pilot participation has been agreed; customer acquisition outcomes have not been established.</p><p>Your position: business planning alone feels replaceable and like a nice-to-have. Do not turn this into an invented pivot story. Previous agency results stay separate from HustlIQ results.</p></section>
  <div className="cs-grid cs-spaced"><section className="cs-panel"><h2>Production boundaries</h2><ul><li>Normal days: 1–2 hours. First recording session: 2–3 hours.</li><li>Comfortable with face-to-camera and screen recording.</li><li>Batch filming suggested Sunday, Wednesday, and Friday/Saturday; exact sessions remain editable.</li><li>Friend can help edit for approximately one month; turnaround under three days.</li><li>11–12 produced weekly is a stretch hypothesis, not a quota.</li><li>Build approximately 8–12 finished reserves when sustainable.</li><li>Arabic long-form is a separate workflow and budget.</li></ul><button onClick={onEdit}>Adjust capacity & start date</button></section><section className="cs-panel"><h2>Recognizable formats</h2><ul><li>Where Would We Find Their First Users?</li><li>Launch to Silence</li><li>Would Reddit Work for This Startup?</li><li>Fix This Founder Reply</li><li>Real Distribution Breakdown</li><li>Find the Conversation</li></ul><p>For Enzo, use looser story patterns: trying something, what happened, a real opinion, an unexpected moment, or an ongoing build.</p></section></div>
  <section className="cs-panel cs-spaced"><h2>Before committing an idea</h2><p>Why would a stranger care? Is there tension, novelty, utility, emotion, or curiosity? Is the identity right? Is it specific and truthful? Does it sound like you? Can we show it? Is it worth the time? Does it repeat recent content? What job does it do?</p><p>One event can create two different angles: Enzo’s personal experience and HustlIQ’s problem analysis. Link related assets; do not duplicate the same video automatically.</p><p>Private messages need permission or anonymization. Public evidence is distinct from interpretation. Unavailable metrics remain unknown.</p></section>
  <section className="cs-panel cs-spaced"><h2>Five-week learning contract</h2><p>Current targets: {settings.enzoWeekly} Enzo + {settings.hustliqWeekly} HustlIQ unique videos per week. One video on three platforms still counts once. Aim for 60–70% planned and 30–40% timely material. Reality can replace the calendar.</p><p>Choose 2–3 repeatable formats for each identity using audience quality, retention, follow conversion, business outcomes, and production cost. Protect customer discovery, sales, building, and founder work when content exceeds capacity.</p></section></>;
}
